version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5216:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    # Добавляем healthcheck для надежности
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/products"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      backend:
        condition: service_healthy